server:
  port: 8002
spring:
  application:
    name: notfand-knife4j
  datasource:
    druid:
      url: jdbc:mysql://39.108.79.4:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml